(function () {
  "use strict";

  function query(selector, root) {
    return (root || document).querySelector(selector);
  }

  function queryAll(selector, root) {
    return Array.prototype.slice.call((root || document).querySelectorAll(selector));
  }

  function setHidden(element, hidden) {
    if (element) {
      element.hidden = hidden;
    }
  }

  function showToast(title, copy) {
    var toast = query("[data-toast]");
    if (!toast) {
      return;
    }
    query("[data-toast-title]", toast).textContent = title;
    query("[data-toast-copy]", toast).textContent = copy;
    toast.hidden = false;
    window.clearTimeout(showToast.timer);
    showToast.timer = window.setTimeout(function () {
      toast.hidden = true;
    }, 3200);
  }

  function initNavigation() {
    var shell = query("[data-app-shell]");
    var backdrop = query("[data-nav-close].app-backdrop");
    if (!shell) {
      return;
    }

    function setNavigation(open) {
      shell.setAttribute("data-nav-open", open ? "true" : "false");
      setHidden(backdrop, !open);
    }

    queryAll("[data-nav-open]").forEach(function (button) {
      button.addEventListener("click", function () {
        setNavigation(true);
      });
    });

    queryAll("[data-nav-close]").forEach(function (button) {
      button.addEventListener("click", function () {
        setNavigation(false);
      });
    });
  }

  function initObjectSearch() {
    var input = query("[data-object-search]");
    var rows = queryAll("[data-object-row]");
    var count = query("[data-object-count]");
    var empty = query("[data-object-empty]");
    if (!input || !rows.length) {
      return;
    }

    input.addEventListener("input", function () {
      var term = input.value.trim().toLowerCase();
      var visible = 0;
      rows.forEach(function (row) {
        var matches = !term || row.getAttribute("data-search").toLowerCase().indexOf(term) !== -1;
        row.hidden = !matches;
        if (matches) {
          visible += 1;
        }
      });
      count.textContent = visible + (visible === 1 ? " table" : " tables");
      empty.hidden = visible !== 0;
    });
  }

  var fieldTypes = {
    text: { storage: "text", format: "plain text", sql: "text" },
    email: { storage: "text", format: "email link", sql: "text" },
    relation: { storage: "foreign key", format: "related record", sql: "bigint REFERENCES public.customers(id)" },
    price: { storage: "numeric", format: "currency", sql: "numeric" },
    select: { storage: "text + check", format: "label", sql: "text" },
    switch: { storage: "boolean", format: "yes / no", sql: "boolean" },
    datetime: { storage: "timestamptz", format: "date and time", sql: "timestamptz" }
  };

  function sqlIdentifier(value, fallback) {
    var normalized = String(value || "")
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "");
    return normalized || fallback;
  }

  function builderColumnMarkup(index) {
    return [
      '<div class="column-card" data-builder-column>',
      '  <label class="app-field">',
      '    <span class="app-label">Column name</span>',
      '    <input class="app-input" type="text" value="New field ' + index + '" data-column-name>',
      "  </label>",
      '  <label class="app-field">',
      '    <span class="app-label">Field</span>',
      '    <select class="app-select" data-field-type>',
      '      <option value="text" selected>Text</option>',
      '      <option value="email">Email</option>',
      '      <option value="relation">Relation</option>',
      '      <option value="price">Price</option>',
      '      <option value="select">Select</option>',
      '      <option value="switch">Switch</option>',
      '      <option value="datetime">Date and time</option>',
      "    </select>",
      "  </label>",
      '  <div class="column-card__inference" data-inference>text · plain text</div>',
      '  <button class="app-button app-button--ghost app-button--icon column-card__remove" type="button" data-remove-builder-column aria-label="Remove new column">',
      '    <span data-wf-icon="trash"></span>',
      "  </button>",
      "</div>"
    ].join("");
  }

  function updateBuilder() {
    var builder = query("[data-table-builder]");
    if (!builder) {
      return;
    }
    var tableName = query("[data-table-name]", builder);
    var identity = query("[data-object-identity]");
    var name = sqlIdentifier(tableName.value, "new_table");
    var lines = ["  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"];

    queryAll("[data-builder-column]", builder).forEach(function (column) {
      var fieldSelect = query("[data-field-type]", column);
      var columnName = query("[data-column-name]", column);
      var config = fieldTypes[fieldSelect.value] || fieldTypes.text;
      query("[data-inference]", column).textContent = config.storage + " · " + config.format;
      var identifier = sqlIdentifier(columnName.value, "new_field");
      if (fieldSelect.value === "relation" && !/_id$/.test(identifier)) {
        identifier += "_id";
      }
      lines.push("  " + identifier + " " + config.sql);
    });

    if (identity) {
      identity.textContent = "public." + name;
    }
    var help = query("#table-name-help");
    if (help) {
      help.innerHTML = 'Created as <span class="app-code">public.' + name + "</span>.";
    }
    var preview = query("[data-sql-preview]");
    if (preview) {
      preview.textContent = "CREATE TABLE public." + name + " (\n" + lines.join(",\n") + "\n);";
    }
  }

  function initTableBuilder() {
    var builder = query("[data-table-builder]");
    var list = query("[data-column-list]");
    if (!builder || !list) {
      return;
    }

    function bindColumn(column) {
      queryAll("input, select", column).forEach(function (control) {
        control.addEventListener("input", updateBuilder);
        control.addEventListener("change", updateBuilder);
      });
      var remove = query("[data-remove-builder-column]", column);
      remove.addEventListener("click", function () {
        if (queryAll("[data-builder-column]", list).length === 1) {
          showToast("Keep one column", "A new table needs at least one usable column.");
          return;
        }
        column.remove();
        updateBuilder();
      });
    }

    queryAll("[data-builder-column]", list).forEach(bindColumn);
    queryAll("[data-add-builder-column]").forEach(function (button) {
      button.addEventListener("click", function () {
        var wrapper = document.createElement("div");
        wrapper.innerHTML = builderColumnMarkup(queryAll("[data-builder-column]", list).length + 1);
        var column = wrapper.firstElementChild;
        list.appendChild(column);
        bindColumn(column);
        if (window.WireframeIcons) {
          window.WireframeIcons.render(column);
        }
        query("[data-column-name]", column).focus();
        updateBuilder();
      });
    });

    builder.addEventListener("submit", function (event) {
      event.preventDefault();
      var tableName = query("[data-table-name]", builder);
      var error = query("[data-table-name-error]", builder);
      if (!tableName.value.trim()) {
        tableName.setAttribute("aria-invalid", "true");
        error.hidden = false;
        tableName.focus();
        return;
      }
      tableName.removeAttribute("aria-invalid");
      error.hidden = true;
      var button = query("[data-create-table]", builder);
      button.disabled = true;
      button.textContent = "Creating table…";
      window.setTimeout(function () {
        window.location.href = "./table.html?created=1";
      }, 450);
    });

    updateBuilder();
  }

  function initQueryState() {
    var params = new URLSearchParams(window.location.search);
    var banner = query("[data-query-banner]");
    var copy = query("[data-query-banner-copy]");
    var tableTitle = query("[data-table-title]");

    if (params.get("created") === "1" && banner) {
      copy.textContent = "Customer orders was created as public.customer_orders.";
      banner.hidden = false;
    }
    if (params.get("imported") === "1" && banner) {
      copy.textContent = "Q3 orders was imported with 248 exact-value records.";
      banner.hidden = false;
      if (tableTitle) {
        tableTitle.textContent = "Q3 orders";
      }
    }
    if (params.get("state") === "error") {
      showDraftError();
    }
  }

  function selectCell(cell) {
    queryAll("[data-cell][aria-selected='true']").forEach(function (selected) {
      selected.removeAttribute("aria-selected");
    });
    cell.setAttribute("aria-selected", "true");
    var grid = query("[data-grid]");
    if (!cell.id) {
      cell.id = "grid-cell-" + (queryAll("[data-cell]").indexOf(cell) + 1);
    }
    if (grid) {
      grid.setAttribute("aria-activedescendant", cell.id);
    }
  }

  function editCell(cell, seed) {
    if (!cell || cell.getAttribute("data-editing") === "true") {
      return;
    }
    var original = cell.getAttribute("data-value") || cell.textContent.trim();
    cell.setAttribute("data-editing", "true");
    cell.innerHTML = "";
    var input = document.createElement("input");
    input.className = "app-input";
    input.setAttribute("aria-label", "Edit cell");
    input.value = seed !== undefined ? seed : original;
    cell.appendChild(input);
    input.focus();
    input.select();

    function finish(commit) {
      if (cell.getAttribute("data-editing") !== "true") {
        return;
      }
      var value = commit ? input.value : original;
      cell.setAttribute("data-value", value);
      cell.removeAttribute("data-editing");
      cell.textContent = value;
      selectCell(cell);
    }

    input.addEventListener("keydown", function (event) {
      if (event.key === "Enter") {
        event.preventDefault();
        finish(true);
      } else if (event.key === "Escape") {
        event.preventDefault();
        finish(false);
      } else if (event.key === "Tab") {
        finish(true);
      }
    });
    input.addEventListener("blur", function () {
      finish(true);
    });
  }

  function initGrid() {
    var grid = query("[data-grid]");
    var cells = queryAll("[data-cell]");
    if (!grid || !cells.length) {
      return;
    }

    cells.forEach(function (cell, index) {
      cell.id = "grid-cell-" + (index + 1);
      cell.addEventListener("click", function () {
        selectCell(cell);
      });
      cell.addEventListener("dblclick", function () {
        editCell(cell);
      });
    });

    grid.addEventListener("keydown", function (event) {
      if (event.target.tagName === "INPUT" || event.target.tagName === "SELECT") {
        return;
      }
      var active = query("[data-cell][aria-selected='true']") || cells[0];
      var index = cells.indexOf(active);
      var next = index;
      if (event.key === "ArrowRight") {
        next = Math.min(cells.length - 1, index + 1);
      } else if (event.key === "ArrowLeft") {
        next = Math.max(0, index - 1);
      } else if (event.key === "ArrowDown") {
        next = Math.min(cells.length - 1, index + 7);
      } else if (event.key === "ArrowUp") {
        next = Math.max(0, index - 7);
      } else if (event.key === "Enter" || event.key === "F2") {
        event.preventDefault();
        editCell(active);
        return;
      } else if (event.key.length === 1 && !event.metaKey && !event.ctrlKey && !event.altKey) {
        event.preventDefault();
        editCell(active, event.key);
        return;
      } else {
        return;
      }
      event.preventDefault();
      selectCell(cells[next]);
      cells[next].scrollIntoView({ block: "nearest", inline: "nearest" });
    });

    selectCell(cells[0]);
  }

  function openContextPanel(mode, value) {
    var panel = query("[data-context-panel]");
    if (!panel) {
      return;
    }
    var columnForm = query("[data-column-form]", panel);
    var rowDetail = query("[data-row-detail]", panel);
    var actions = query("[data-column-panel-actions]", panel);
    var title = query("[data-context-title]", panel);

    if (mode === "row") {
      columnForm.hidden = true;
      rowDetail.hidden = false;
      actions.hidden = true;
      title.textContent = "Order " + value;
      query("[data-row-detail-id]", rowDetail).textContent = "Order " + value;
    } else {
      columnForm.hidden = false;
      rowDetail.hidden = true;
      actions.hidden = false;
      title.textContent = "Configure " + (value === "email" ? "Email" : "column");
    }
    panel.setAttribute("data-open", "true");
    panel.setAttribute("aria-hidden", "false");
    panel.removeAttribute("inert");
    query("[data-close-context]", panel).focus();
  }

  function closeContextPanel() {
    var panel = query("[data-context-panel]");
    if (panel) {
      panel.setAttribute("data-open", "false");
      panel.setAttribute("aria-hidden", "true");
      panel.setAttribute("inert", "");
    }
  }

  function initColumnAndRowPanels() {
    var menu = query("[data-context-menu]");
    queryAll("[data-header-menu]").forEach(function (button) {
      button.addEventListener("click", function (event) {
        event.stopPropagation();
        var rect = button.getBoundingClientRect();
        menu.hidden = false;
        menu.setAttribute("data-column", button.getAttribute("data-header-menu"));
        menu.style.top = Math.min(window.innerHeight - 210, rect.bottom + 5) + "px";
        menu.style.left = Math.min(window.innerWidth - 232, Math.max(10, rect.left - 170)) + "px";
      });
    });

    queryAll("[data-open-column-panel]").forEach(function (button) {
      button.addEventListener("click", function () {
        if (menu) {
          menu.hidden = true;
        }
        openContextPanel("column", button.getAttribute("data-open-column-panel") || "email");
      });
    });

    queryAll("[data-open-row]").forEach(function (button) {
      button.addEventListener("click", function () {
        openContextPanel("row", button.getAttribute("data-open-row"));
      });
    });

    queryAll("[data-close-context]").forEach(function (button) {
      button.addEventListener("click", closeContextPanel);
    });

    var saveColumn = query("[data-save-column]");
    if (saveColumn) {
      saveColumn.addEventListener("click", function () {
        var name = query("[data-column-panel-name]").value.trim() || "Email";
        var field = query("[data-column-panel-field]").value.toLowerCase();
        var required = query("[data-column-required]").checked;
        query("[data-email-header-title]").textContent = name;
        query("[data-email-header-meta]").textContent = field + (required ? " · required" : "");
        closeContextPanel();
        showToast("Column updated", name + " keeps PostgreSQL text storage and its selected display format.");
      });
    }

    document.addEventListener("click", function (event) {
      if (menu && !menu.hidden && !menu.contains(event.target) && !event.target.closest("[data-header-menu]")) {
        menu.hidden = true;
      }
    });
  }

  function initAddColumnDialog() {
    var dialog = query("[data-add-column-dialog]");
    var emptyHeader = query("[data-empty-header]");
    if (!dialog || !emptyHeader) {
      return;
    }

    function openDialog() {
      dialog.showModal();
      window.setTimeout(function () {
        query("[data-new-column-name]", dialog).focus();
      }, 0);
    }

    function closeDialog() {
      dialog.close();
    }

    emptyHeader.addEventListener("dblclick", openDialog);
    emptyHeader.addEventListener("keydown", function (event) {
      if (event.key === "Enter" || event.key === " ") {
        event.preventDefault();
        openDialog();
      }
    });
    queryAll("[data-close-dialog]", dialog).forEach(function (button) {
      button.addEventListener("click", closeDialog);
    });
    query("[data-add-column-form]", dialog).addEventListener("submit", function (event) {
      event.preventDefault();
      var input = query("[data-new-column-name]", dialog);
      var error = query("[data-new-column-error]", dialog);
      if (!input.value.trim()) {
        input.setAttribute("aria-invalid", "true");
        error.hidden = false;
        input.focus();
        return;
      }
      input.removeAttribute("aria-invalid");
      error.hidden = true;
      closeDialog();
      showToast("Column added", input.value.trim() + " was added with text storage.");
      input.value = "";
    });
  }

  function showDraftError() {
    var cell = query("[data-draft-email-cell]");
    var input = query("[data-draft-email]");
    var error = query("[data-draft-error]");
    if (!cell || !input || !error) {
      return;
    }
    cell.setAttribute("data-invalid", "true");
    input.setAttribute("aria-invalid", "true");
    error.hidden = false;
  }

  function clearDraftError() {
    var cell = query("[data-draft-email-cell]");
    var input = query("[data-draft-email]");
    var error = query("[data-draft-error]");
    if (!cell || !input || !error) {
      return;
    }
    cell.removeAttribute("data-invalid");
    input.removeAttribute("aria-invalid");
    error.hidden = true;
  }

  function promoteDraft() {
    var row = query("[data-draft-row]");
    var email = query("[data-draft-email]");
    if (!row || !email) {
      return;
    }
    if (!email.value.trim() || email.value.indexOf("@") === -1) {
      showDraftError();
      email.focus();
      showToast("Record stays in drafts", "Enter a valid email before this row can be added to PostgreSQL.");
      return;
    }
    clearDraftError();
    var draftCells = queryAll(".data-grid__cell--draft", row);
    draftCells.forEach(function (cell) {
      cell.classList.remove("data-grid__cell--draft");
    });
    var rowHeader = query("[role='rowheader']", row);
    rowHeader.textContent = "5";
    var inputs = queryAll("input", row);
    inputs.forEach(function (input) {
      input.parentElement.textContent = input.value;
    });
    var select = query("select", row);
    if (select) {
      select.parentElement.innerHTML = '<span class="status-pill">' + select.value + "</span>";
    }
    var idCell = queryAll("[role='gridcell']", row)[0];
    idCell.textContent = "1085";
    var actionCell = queryAll("[role='gridcell']", row).slice(-1)[0];
    actionCell.innerHTML = '<button class="header-button" type="button" data-open-row="1085" aria-label="Open order 1085"><span data-wf-icon="chevron-right"></span></button>';
    actionCell.querySelector("button").addEventListener("click", function () {
      openContextPanel("row", "1085");
    });
    if (window.WireframeIcons) {
      window.WireframeIcons.render(actionCell);
    }
    row.removeAttribute("data-draft-row");
    var toolbarSave = query("[data-save-draft-toolbar]");
    if (toolbarSave) {
      toolbarSave.hidden = true;
    }
    showToast("Record added", "Order 1085 was accepted and added to the PostgreSQL table.");
  }

  function initDraftRow() {
    var saveButtons = queryAll("[data-save-draft]");
    var email = query("[data-draft-email]");
    if (!saveButtons.length || !email) {
      return;
    }
    saveButtons.forEach(function (save) {
      save.addEventListener("click", promoteDraft);
    });
    email.addEventListener("input", function () {
      if (email.value.trim()) {
        clearDraftError();
      }
    });
    var focusDraft = query("[data-focus-draft]");
    if (focusDraft) {
      focusDraft.addEventListener("click", function () {
        var customer = query("[data-draft-customer]");
        if (customer) {
          customer.focus();
          customer.select();
        }
      });
    }
  }

  function initImportWizard() {
    var wizard = query("[data-import-wizard]");
    if (!wizard) {
      return;
    }
    var step = 1;

    function updateStep(nextStep) {
      step = Math.max(1, Math.min(3, nextStep));
      wizard.setAttribute("data-step", String(step));
      queryAll("[data-import-screen]", wizard).forEach(function (screen) {
        screen.hidden = Number(screen.getAttribute("data-import-screen")) !== step;
      });
      queryAll("[data-step-indicator]", wizard).forEach(function (indicator) {
        var number = Number(indicator.getAttribute("data-step-indicator"));
        indicator.setAttribute("data-active", number === step ? "true" : "false");
        indicator.setAttribute("data-complete", number < step ? "true" : "false");
      });
    }

    queryAll("[data-import-source]", wizard).forEach(function (button) {
      button.addEventListener("click", function () {
        queryAll("[data-import-source]", wizard).forEach(function (other) {
          other.setAttribute("aria-pressed", other === button ? "true" : "false");
        });
        var source = button.getAttribute("data-import-source");
        var summary = query("[data-source-summary]", wizard);
        var strong = query("strong", summary);
        var meta = query(".app-meta", summary);
        if (source === "xlsx") {
          strong.textContent = "Q3-orders.xlsx";
          meta.textContent = "248 rows · 6 columns · 51 KB";
        } else if (source === "google") {
          strong.textContent = "Q3 Orders";
          meta.textContent = "Google Sheets · 248 rows · latest values";
        } else {
          strong.textContent = "Q3-orders.csv";
          meta.textContent = "248 rows · 6 columns · 38 KB";
        }
      });
    });

    queryAll("[data-import-next]", wizard).forEach(function (button) {
      button.addEventListener("click", function () {
        updateStep(step + 1);
      });
    });
    queryAll("[data-import-back]", wizard).forEach(function (button) {
      button.addEventListener("click", function () {
        updateStep(step - 1);
      });
    });

    var run = query("[data-import-run]", wizard);
    if (run) {
      run.addEventListener("click", function () {
        var ready = query("[data-import-ready]", wizard);
        var progress = query("[data-import-progress]", wizard);
        var success = query("[data-import-success]", wizard);
        var actions = query("[data-import-final-actions]", wizard);
        ready.hidden = true;
        actions.hidden = true;
        progress.hidden = false;
        window.setTimeout(function () {
          progress.hidden = true;
          success.hidden = false;
        }, 900);
      });
    }

    updateStep(1);
  }

  function initGlobalKeys() {
    document.addEventListener("keydown", function (event) {
      if (event.key !== "Escape") {
        return;
      }
      var menu = query("[data-context-menu]");
      if (menu) {
        menu.hidden = true;
      }
      closeContextPanel();
      var dialog = query("[data-add-column-dialog]");
      if (dialog && dialog.open) {
        dialog.close();
      }
    });
  }

  document.addEventListener("DOMContentLoaded", function () {
    initNavigation();
    initObjectSearch();
    initTableBuilder();
    initQueryState();
    initGrid();
    initColumnAndRowPanels();
    initAddColumnDialog();
    initDraftRow();
    initImportWizard();
    initGlobalKeys();
  });
})();
